name: clone dependencies
description: dependencies

runs:
 using: composite
 steps:
  - name: clone susfs and change commit if necessary, and clone kernel patches
    shell: bash
    run: |
     ANYKERNEL_BRANCH="gki-2.0"
     
     git clone https://github.com/WildKernels/kernel_patches.git
     git clone https://github.com/WildKernels/AnyKernel3.git -b "$ANYKERNEL_BRANCH"
